version: "3.8"

services:
  master:
    image: redis-py-master
    ports:
      - "6379:6379"

  slave:
    image: redis-py-slave
    depends_on:
      - "master"
    ports:
      - "6380:6380"

  sentinel_1:
    image: redis-py-sentinel-1
    depends_on:
      - "slave"
    ports:
      - "26379:26379"

  sentinel_2:
    image: redis-py-sentinel-2
    depends_on:
      - "slave"
    ports:
      - "26380:26380"

  sentinel_3:
    image: redis-py-sentinel-3
    depends_on:
      - "slave"
    ports:
      - "26381:26381"

  test:
    build: .
    depends_on:
      - "sentinel_3"
    environment:
      REDIS_MASTER_HOST: master
      REDIS_MASTER_PORT: 6379
      CI:
      CI_BUILD_ID:
      CI_BUILD_URL:
      CI_JOB_ID:
      CODECOV_ENV:
      CODECOV_SLUG:
      CODECOV_TOKEN:
      CODECOV_URL:
      SHIPPABLE:
      TRAVIS:
      TRAVIS_BRANCH:
      TRAVIS_COMMIT:
      TRAVIS_JOB_ID:
      TRAVIS_JOB_NUMBER:
      TRAVIS_OS_NAME:
      TRAVIS_PULL_REQUEST:
      TRAVIS_REPO_SLUG:
      TRAVIS_TAG:
      VCS_BRANCH_NAME:
      VCS_COMMIT_ID:
      VCS_PULL_REQUEST:
      VCS_SLUG:
      VCS_TAG:
